### ISSUE TITLE
New Feature Request - Output Sort Order

### ISSUE THREAD

**Issue by BitPsycho** [BSData/catalogue-development#37] opened 2019-01-14 10:43 UTC
Would be nice if we could add a display/output sort number to items like ( selection entry, selection entry groups and shared rules ).  Currently it seems that the display is simply done alphabetically.

This sort number should then be used for:

- selections - eg for a spell caster I want the spell groups to be displayed first as entry 
-  roster output - eg a unit profile should be displayed before any other profiles (like weapons )

For the moment I managed to obtain the above by using a little trick - starting the name with a space ensures that they get sorted first - but that only works for 1 item of course.

Thanks,

Steven

**Comment by amis92** [comment] 2019-01-14 14:49
I think this is a duplicate of https://github.com/BattleScribe/Release/issues/27 :)

**Comment by amis92** [comment] 2019-05-05 20:47
Closing as duplicate

**Closed by amis92** 2019-05-05 20:47 UTC
Labels: duplicate, enhancement
