### ISSUE TITLE
New repo:Warhammer Fantasy Battle 6th Edition

### ISSUE THREAD

**Issue by Ergofarg** [BSData/catalogue-development#147] opened 2020-10-31 11:19 UTC
https://github.com/Ergofarg/Warhammer-Fantasy-6th-edition

Working on it. Needs own listing not grouped with the other editions.

**Comment by OftKilted** [comment] 2020-11-02 11:47
Duplicate of #146

**Comment by DrTobogganMD** [comment] 2020-11-15 23:42
This has already been denied with reason given. The repo data already exists within the WHFB repo.

**Closed by DrTobogganMD** 2020-11-15 23:42 UTC
Labels: new repo
