### ISSUE TITLE
New repo: Warhammer The Old World

### ISSUE THREAD

**Issue by edvinullman** [BSData/catalogue-development#235] opened 2024-01-27 19:50 UTC
Please consider opening a repo for The Old World, the Old-World-Builder app is such a starved alternative.

**Comment by amis92** [comment] 2024-01-27 19:54
@edvinullman please see https://github.com/BSData/catalogue-development/issues/234#issuecomment-1880139360

duplicate of #234

**Closed as not planned** 2024-01-27 19:54 UTC
Labels: new repo

**Comment by edvinullman** [comment] 2024-01-27 19:59
@amis92 thanks! Missed that one!
